[package]
name = "lesser-cam"
version = "0.1.0"
edition = "2024"
build = "build.rs" 

[dependencies]
tonic-reflection = "0.9.2"
web-view = { git = "https://github.com/huytd/web-view" }

tonic = "*"
prost = "0.13"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tonic-web = "0.12.3"
tower-http = { version = "0.6.2", features = ["cors"] }
http = "1.1.0"
tonic-health = "0.12.3"

[build-dependencies]
tonic-build = "0.9.2"
tonic-prost-build = "*"