[package]
name = "lesser-cam"
version = "0.1.0"
edition = "2024"

[dependencies]
web-view = { git = "https://github.com/huytd/web-view" }
axum = { version = "0.6", features = ["ws"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"